### ISSUE TITLE
About severity levels in copying

### ISSUE THREAD

**Issue by vineeshvs** [dilawar/iitb_moodle_check_assignment#1]
Hi,

If the student is copying a file and renaming two or three variables and comment some lines, it will be categorized only high_level severity case (40-60% copying). Is it possible to put them in identical severity (>80%) or very_high_severity (60-80%) case?

Thanks

**Comment by dilawar** [comment]
Unfortunately no. If a student adds comments, I divide the index by the size of
total text and I have no way of telling which file is being copied to. 

I think I can do both side comparisons ( A Vs B and B Vs A) and take the maximum
of both. 

If you pass on some sample files to work with, it would be great.

**Comment by vineeshvs** [comment]
Hi,

I have mailed you the files from vineeshvsjobs@gmail.com

Thanks

**Comment by dilawar** [comment]
Commit 067473577d7c5a072ed3f86a52f8d5447890b086 fixes this. The severity will be much higher. This is done by comparing words before using the difflib. 

If set of unique words in each file has larger intersection than difflib result, the larger result is returned.

Also multiple whitespaces and newlines are replaced by a single whitespace. That also improved the result returned by difflib.

For the sample files @vineeshvs  sent me, the current matching index is now 0.769.  

In case, these changes might affect the other comparisons, please let me know. I hope that you are likely to see a increased value of match for cases where there is already a match.
